receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]
          max_age: 7200
        endpoint: 0.0.0.0:55681

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_WRITE_KEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"

extensions:
service:
  extensions:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlp
        # Uncomment below to enable console logging in the exporter
        # - logging
