
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:55680"
      http:
        endpoint: "0.0.0.0:55681"
processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_WRITE_KEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"

extensions:
  zpages: {}
service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, jaeger, otlp]
